### ISSUE TITLE
intercept-build does not work on git without --override-compiler

### ISSUE THREAD

**Issue by Sarcasm** [rizsotto/scan-build#51]
Hello,

I was trying out `intercept-build` on git 2.9.2 to experiment with the tool.

If I use `bear`, I can do the following to get a compilation database:

```
echo DEVELOPER=1 >> config.mak
make configure
bear make -j9
```

If I try to substitute `bear` with `intercept-build`, that results in a crash:

```
$ intercept-build make -j9          
GIT_VERSION = 2.9.2
    * new build flags
# command exited with status 245
```

If I use `intercept-build` with the `--override-compiler` option, then it's working fine:

```
intercept-build --override-compiler make -j9
```

Maybe it's not a bug but the crash surprised me.
I have to say I'm not sure what `--override-compiler` exactly do,
but since it is in the "advanced options" category I thought it should not be needed.

What do you think,
is it the expected behavior?

Thanks.

**Comment by rizsotto** [comment]
thank you Guillaume, will look at it as soon as i'm back from vacation.

**Comment by rizsotto** [comment]
could reproduce the bug. got "corrupted double-linked list" error from libc before the crash. don't really understand what caused it. as a fix, i reverted to an older version of the `ear.c`. now it works fine. the fix is on the devel branch currently. will make a new release soon. (please feel free to reopen this ticket if it still misbehaves for you.)

**Comment by Sarcasm** [comment]
It's working great now, thank you!
